config/routes.rb
Rails.application.routes.draw do

  get 'users_backoffice/test_questions'
  namespace :site do
    get 'welcome/index'
    get 'search',                       to: 'search#questions'
    get 'subject/:subject_id/:subject', to: 'search#subject', as: "search_subject"
    post 'answer',                      to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile',                            to: 'profile#edit'
    patch 'profile',                          to: 'profile#update'
    get 'zip_code',                           to: 'zip_code#show'
    get 'tests/:test_id/user_tests/results',  to: 'user_tests#results'

    #nested resources 
    resources :tests do
      resources :user_tests
    end 

  end
  namespace :admins_backoffice do
    get 'welcome/index' 
    resources  :admins 
    resources  :subjects 
    resources  :questions 
    resources  :tests 
    resources  :test_questions
  end

  devise_for :admins, skip: [:registrations]
  devise_for :users

  get 'inicio',     to: 'site/welcome#index'
  get 'backoffice', to: 'admins_backoffice/welcome#index'

  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
  has_many :tests

end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit, :update, :destroy]
  # before_action :params_admin, only: [:update]
  
  def index
    @admins = Admin.all.page(params[:page]).per(5)
  end

  def edit
   
  end

  def update

    if @admin.update(params_admin)
      if @admin.update(params_admin)
        AdminMailer.update_email(current_admin, @admin).deliver_now
        redirect_to admins_backoffice_admins_path, notice: "Administrador
       atualizado com sucesso!"
        else
        render :edit
      end
       
      redirect_to admins_backoffice_admins_path, notice: "Administrador atualizado com sucesso!"
    else
      render :edit
    end
  end

  def create
    @admin = Admin.new(params_admin)

    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Administrador cadastrado com sucesso!"
    else
      render :edit
    end
  end

  def new
    @admin = Admin.new
  end

  def destroy
    
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Administrador excluido com sucesso!"
    else
      render :index
    end
  end

  private
    def set_admin
      @admin = Admin.find(params[:id])
    end

    def params_admin
      params.require(:admin).permit(:email, :password, :password_confirmation)
    end

    def verify_password
      if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
        params[:admin].extract!(:password, :password_confirmation)
      end

    end
  end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
before_action :set_question, only: [:edit, :update, :destroy]
before_action :get_subjects, only: [:new, :edit]

  def index
    @questions = Question.includes(:subject).order(:description).page(params[:page])
  end

  def new
    @question = Question.new
   
  end

  def create
    @question = Question.new(params_question)
    if @question.save
      redirect_to admins_backoffice_questions_path, notice: "Questão cadastrada com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice: "Questão atualizada com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      redirect_to admins_backoffice_questions_path, notice: "Questão excluída com sucesso!"
    else
     render :index
    end
  end

  private

  def params_question
    params.require(:question).permit(:description, :subject_id, :weight,
    answers_attributes: [:id, :description, :correct, :_destroy])
  end
  def set_question
    @question = Question.find(params[:id])
  end

  def get_subjects
    @subjects = Subject.all
  end
end
   

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: [:edit, :update, :destroy]
  # before_action :params_subject, only: [:update]
  
  def index
    respond_to do |format|
     format.html { @subjects = Subject.all.order(:description).page(params[:page]).per(5)}
     format.pdf { @subjects = Subject.all.order(:description)}
     format.json { @subjects = Subject.all.order(:description)}
    end
  end

  def edit
   
  end

  def update
  
    if @subject.update(params_subject)
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área atualizado com sucesso!"
    else
      render :edit
    end
  end

  def create
    @subject = Subject.new(params_subject)

    if @subject.save
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área cadastrado com sucesso!"
    else
      render :edit
    end
  end

  def new
    @subject = Subject.new
  end

  def destroy
    if @subject.destroy
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área excluido com sucesso!"
    else
      render :index
    end
  end

  private
    def set_subject
      @subject = Subject.find(params[:id])
    end

    def params_subject
      params.require(:subject).permit(:description)
    end
  
  end

app/controllers/admins_backoffice/test_questions_controller.rb
class AdminsBackoffice::TestQuestionsController < AdminsBackofficeController
 
  def index
    @questions = Question.where(subject_id: params[:id]).all
    @test = Test.find(params[:test])
  end

  private

  def params_test
    params.require(:test).permit(:subject_id, :id)
  end

end

app/controllers/admins_backoffice/tests_controller.rb
class AdminsBackoffice::TestsController < AdminsBackofficeController
  before_action :set_test,      only: [:edit, :update, :destroy]
  before_action :params_test,   only: [:update]
  before_action :get_subjects,  only: [:new, :edit]
  before_action :get_questions, only: [:new, :edit]
  
  def index
    @tests = Test.all.includes(:subject).includes(:questions)
  end

  def edit
    questions_ids = @test.question_ids
    @questions = Question.find(questions_ids)
  end

  def new
    @test = Test.new
  end

  def update
    if params[:test]    
      if @test.update(params_test)
        redirect_to edit_admins_backoffice_test_path(@test), notice: "Prova atualizada com sucesso!"
      else
        render :edit
      end
    else
      redirect_to edit_admins_backoffice_test_path(@test), notice: "Prova não pode ficar sem questões!"
    end
  end

  def create
    @test = Test.new(params_test)

    if @test.save
      redirect_to edit_admins_backoffice_test_path(@test), notice: "Prova criada com sucesso! Selecione as questões"
    else
      render :edit
    end
  end


  def destroy
    @test.questions.clear
    if @test.destroy
      redirect_to admins_backoffice_tests_path, notice: "Avaliação excluido com sucesso"
    else
      render :index
    end
  end

  private
  
    def set_test
      @test = Test.find(params[:id])
    end

    def params_test
      if params[:test]
        params.require(:test).permit(:name, :subject_id, question_ids: [])
      else
        params.permit(:id)
      end
    end

    def get_subjects
      @subjects = Subject.all
    end

    def get_questions
      @questions = Question.all
    end

end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
    @total_users = AdminStatistic.total_users
    @total_questions = AdminStatistic.total_questions
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/test_questions_helper.rb
module AdminsBackoffice::TestQuestionsHelper
end

app/helpers/admins_backoffice/tests_helper.rb
module AdminsBackoffice::TestsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(object = nil,method = nil)
    if object && method
      object.model.human_attribute_name(method)
    else
      "Informe corretamente os atributos!"
    end
  end
end

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
            locals: {action_message: 'Editando'} %>

app/views/admins_backoffice/subjects/index.html.erb
<h1>Listando Assuntos/Áreas</h1>


<div class="table-responsive">
    <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4"><div class="row"><div class="col-sm-12 col-md-6"><div class="dataTables_length" id="dataTable_length"><label>Show <select name="dataTable_length" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div></div><div class="col-sm-12 col-md-6"><div id="dataTable_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="dataTable"></label></div></div></div><div class="row"><div class="col-sm-12"><table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
        <thead>
            <tr role="row">
              <th 
                class="sorting sorting_asc" 
                tabindex="0" 
                aria-controls="dataTable" 
                rowspan="1" colspan="1" 
                aria-sort="ascending" a
                ria-label="Name: activate to sort column descending" 
                style="width: 169px;">
                  #
                </th>
                <th class="sorting" 
                  tabindex="0" aria-controls="dataTable" r
                  owspan="1" 
                  colspan="1" aria-label="Position: activate to sort column ascending" 
                  style="width: 259px;">
                  <%= translate_attribute(@subjects, :description) %>
                  </th>
                <th 
                  class="sorting" 
                  tabindex="0" 
                  aria-controls="dataTable" 
                  rowspan="1" 
                  colspan="1" 
                  aria-label="Office: activate to sort column ascending"
                  style="width: 121px;">
                    <%= link_to new_admins_backoffice_subject_path, class: "btn btn-success btn-circle" do %>
                      <i class="fa fa-plus"></i>
                    <% end%>
                    <%= link_to admins_backoffice_subjects_path(format: :pdf), class: "btn btn-danger btn-circle" do %>
                      <i class="fa fa-file-pdf-o"></i>
                    <% end%>
                   </th>
                  <th 
                    class="sorting" 
                    tabindex="0" 
                    aria-controls="dataTable" 
                    rowspan="1" colspan="1"
                    aria-label="Age: activate to sort column ascending" 
                    style="width: 54px;">
                
                  </th><th class="sorting" 
                  tabindex="0" aria-controls="dataTable" 
                  rowspan="1" 
                  colspan="1" aria-label="Start date: activate to sort column ascending" 
                  style="width: 114px;">Start date</th><th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 102px;">
                  Salário</th></tr>
        </thead>
        <tfoot>
            <tr><th rowspan="1" colspan="1">#</th><th rowspan="1" colspan="1">Position</th><th rowspan="1" colspan="1">Office</th><th rowspan="1" colspan="1">Age</th><th rowspan="1" colspan="1">Start date</th><th rowspan="1" colspan="1">Salary</th></tr>
        </tfoot>
        <tbody>
        
        <% @subjects.each do |subject| %>
          <tr class="odd">
            <td class="sorting_1"> <%= subject.id %> </td>
            <td> <%= subject.description %></td>
            <td> 
              <%= link_to edit_admins_backoffice_subject_path(subject), class: "btn btn-primary btn-circle" do %>
                <i class="fa fa-edit"></i>
              <% end%>
              <%= link_to admins_backoffice_subject_path(subject), 
                method: :delete, 
                class:"btn btn-danger btn-circle", 
                data: { confirm: t('messages.confirm_with', item: subject.description.truncate(15)) } do %>
                  <i class="fa fa-minus"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
    <div class="text-center">
      <%= paginate @subjects %>
    </div>

    
    </table>
    <%# </div></div><div class="row"><div class="col-sm-12 col-md-5"><div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div></div><div class="col-sm-12 col-md-7"><div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate"><ul class="pagination"><li class="paginate_button page-item previous disabled" id="dataTable_previous"><a href="#" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li><li class="paginate_button page-item active"><a href="#" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">1</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="2" tabindex="0" class="page-link">2</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="3" tabindex="0" class="page-link">3</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="4" tabindex="0" class="page-link">4</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="5" tabindex="0" class="page-link">5</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="6" tabindex="0" class="page-link">6</a></li><li class="paginate_button page-item next" id="dataTable_next"><a href="#" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a></li></ul></div></div></div></div> %>
</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form', 
            locals: {action_message: 'Novo'} %>