config/routes.rb
Rails.application.routes.draw do

  get 'users_backoffice/test_questions'
  namespace :site do
    get 'welcome/index'
    get 'search',                       to: 'search#questions'
    get 'subject/:subject_id/:subject', to: 'search#subject', as: "search_subject"
    post 'answer',                      to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile',                            to: 'profile#edit'
    patch 'profile',                          to: 'profile#update'
    get 'zip_code',                           to: 'zip_code#show'
    get 'tests/:test_id/user_tests/results',  to: 'user_tests#results'

    #nested resources 
    resources :tests do
      resources :user_tests
    end 

  end
  namespace :admins_backoffice do
    get 'welcome/index' 
    resources  :admins 
    resources  :subjects 
    resources  :questions 
    resources  :tests 
    resources  :test_questions
  end

  devise_for :admins, skip: [:registrations]
  devise_for :users

  get 'inicio',     to: 'site/welcome#index'
  get 'backoffice', to: 'admins_backoffice/welcome#index'

  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_test.rb
class UserTest < ApplicationRecord
  belongs_to :user
  belongs_to :test

  has_many :user_test_answers
  has_many :answers, through: :user_test_answers

  has_many :test_questions
  has_many :questions, through: :test_questions

  accepts_nested_attributes_for :user_test_answers

  #método calcular a nota
  def self.calc_grade(user_id, test_id)
    user_test = UserTest.where(user_id: user_id, test_id: test_id)[0] #pega o user 
    answers = user_test.answers

    correct_answers = 0
    all_questions_weight = 0 

    answers.each do |answer|
      if answer.correct?
        correct_answers += answer.question.weight
        all_questions_weight += answer.question.weight
      else 
        all_questions_weight += answer.question.weight
      end
    end
      return grade = (correct_answers / all_questions_weight.to_f) * 10
  end
  
  def self.search_test_answers(user_id, test_id)
    return UserTest.where(user_id: user_id, test_id: test_id)[0].answers.to_a
  end

end

app/controllers/users_backoffice/profile_controller.rb
class UsersBackoffice::ProfileController < UsersBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_user

  def edit
    @user.build_user_profile if @user.user_profile.blank?
  end

  def update
  
    if @user.update(params_user)
      bypass_sign_in(@user)
      unless params_user[:user_profile_attributes][:avatar]
        redirect_to users_backoffice_profile_path, notice: "avatar atualizado com sucesso!"
      end
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def params_user
    params.require(:user).permit(:first_name, :last_name ,:email, :password, :password_confirmation,
    user_profile_attributes: [:id, :address, :gender, :birthdate, :avatar, :zip_code])
  end

  def verify_password
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].extract!(:password, :password_confirmation)
    end

  end
end

app/controllers/users_backoffice/tests_controller.rb
class UsersBackoffice::TestsController < UsersBackofficeController

  def index
    @tests = Test.all.includes(:subject).includes(:questions)
    @current_user_tests = current_user.user_tests.to_a
  end
  
end

app/controllers/users_backoffice/user_tests_controller.rb
class UsersBackoffice::UserTestsController < UsersBackofficeController
  before_action :set_test, only: [:new, :results, :show]
  before_action :set_user_test, only: [:results, :show]

  def new
    if current_user.test_ids.include?(params[:test_id].to_i) #verificar se usuario ta tentando entrar pela url
      redirect_to "/users_backoffice/tests/#{params[:test_id]}/user_tests/show"
    end
    
    @user_test = current_user.user_tests.new
    @user_test.user_test_answers.new
   end

  def create 
    @user_test = current_user.user_tests.new(params_test)

    if  @user_test.save
      @user_test.grade = UserTest.calc_grade(current_user.id, params[:test_id])
      redirect_to "/users_backoffice/tests/#{params[:test_id]}/user_tests/results"
    else
      render :new
    end
   end

  def results

  end

  def show
    @test_answers = UserTest.search_test_answers(current_user.id, params[:test_id])
  end

  private

  def set_test
    @test = Test.find(params[:test_id])
  end

  def set_user_test
    @user_test = UserTest.find_by(test_id: params[:test_id])
  end

  def params_test
    params.require(:user_test).permit(:test_id, user_test_answers_attributes: [:answer_id])
  end

end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
    def index
        @user_statistic = UserStatistic.find_or_create_by(user: current_user)
    end
end

app/controllers/users_backoffice/zip_code_controller.rb
class UsersBackoffice::ZipCodeController < UsersBackofficeController
  def show  
    @cep = CEP.new(params[:zip_code])
  end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  before_action :build_profile
  layout 'users_backoffice'

  private 

  def build_profile
    current_user.build_user_profile if current_user.user_profile.blank?
  end
end

app/helpers/users_backoffice/profile_helper.rb
module UsersBackoffice::ProfileHelper
  def gender_select(user, current_gender)
    user.user_profile.gender == current_gender ? 'btn-primary' : 'btn-default'
  end
end

app/helpers/users_backoffice/test_questions_helper.rb
module UsersBackoffice::TestQuestionsHelper
end

app/helpers/users_backoffice/tests_helper.rb
module UsersBackoffice::TestsHelper
end

app/helpers/users_backoffice/user_test_answers_helper.rb
module UsersBackoffice::UserTestAnswersHelper
end

app/helpers/users_backoffice/user_tests_helper.rb
module UsersBackoffice::UserTestsHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice/zip_code_helper.rb
module UsersBackoffice::ZipCodeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
  def avatar_url
    avatar = current_user.user_profile.avatar

    avatar.attached? ? avatar : 'img.jpg'
  end

  def date_formatter(to_date)
    DateTime.parse(to_date).localtime.strftime '%d-%m-%Y %H:%M:%S'
  end


end

app/views/users_backoffice/user_tests/new.html.erb
<div>
  <h3> <%= @test.name %> </h3>
</div>

<%= form_for([:users_backoffice, @test, @user_test], local: true) do |form| %>
  <%= form.hidden_field :test_id, :value => @test.id %>
  <% @test.questions.each_with_index do |question, index| %>
    <div class="card w-75">
      <h5 class="card-header"> Questão <%= index + 1 %> </h5>
      <div class="card-body">
        <h5 class="card-title"> <%= question.description %> </h5>
        <hr>
        <ul style="list-style:none;">
        <%= form.fields_for :user_test_answers do |form_test_answer| %>
            <% question.answers.each do |answer|%>
              <li> 
                <%= form_test_answer.radio_button :answer_id, answer.id %> 
                <%#= check_box_tag "[answer_ids][]",  answer.id %> 
                <span class="card-text"><%= answer.description %></span>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <%= form.submit "Finalizar avaliação", 
    class:"btn btn-primary mt-5", 
    method: "post",
    data: { confirm: "Você deseja realmente finalizar a avaliação?" }
  %>
  
<% end %>

app/views/users_backoffice/user_tests/results.html.erb
<h1>Resultado para Avaliação <%= @test.id %></h1>

<h2 class="display-2"><%= @user_test.grade.round(2) %></h2>

<% if (@user_test.grade > 7) %>
  <h3>Parabêns! Você foi aprovado na avaliação!</h3>
<% end %>
<% unless %>
  <h3>Você reprovou :(</h3>
<% end %>

<hr>

<%= link_to "Visualizar avaliação", "/users_backoffice/tests/#{@test.id}/user_tests/show", class:"btn btn-primary" %>

<%= link_to 'Voltar para Avaliações', users_backoffice_tests_path, class:"btn btn-light" %>

app/views/users_backoffice/user_tests/show.html.erb
<div>
  <h3> <%= @test.name %> </h3>
</div>

<% @test.questions.each_with_index do |question, index| %>
<div class="card w-75">
  <h5 class="card-header"> Questão <%= index + 1 %> </h5>
  <div class="card-body">
    <h5 class="card-title"> <%= question.description %> </h5>
    <hr>
    <ul style="list-style:none;">
      <% question.answers.each do |answer|%>
        <li> 
          <%= radio_button_tag "form_questions[#{question.id}][]", answer.id, (@test_answers), disabled: true %>
          <span class="<%= answer.correct? ? 'w-100 bg-green' : 'w-100 bg-red' %>">
            <%= answer.description %>
          </span>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<% end %>
<%= link_to 'Voltar para Avaliações', users_backoffice_tests_path, class:"btn btn-primary mt-5" %>